Isi2.Projekt/Isi2.Projekt.Web/Models/ViewModels/EntryViewModel.cs
using Isi2.Projekt.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Isi2.Projekt.Web.Models.ViewModels
{
    public class EntryViewModel
    {
        public IEnumerable<EntryContract> Entries { get; set; }

        public UserContract CurentUser { get; set; }

    }
}

Isi2.Projekt/Isi2.Projekt.Web/Controllers/AdministratorController.cs
using Isi2.Projekt.Contracts;
using Isi2.Projekt.Web.Code;
using Isi2.Projekt.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Isi2.Projekt.Web.Controllers
{
    [Authorize]
    [AccessGroup]
    public class AdministratorController : Controller
    {
        //
        // GET: /Admnistrator/
        private readonly IService _service = WindsorContainerAccess.GetContainer().Resolve<IService>();


        public ActionResult Index()
        {
            UserContract model = default(UserContract);
            var users = _service.GetUsers(new Contracts.User.UserFilterContract() {Login = User.Identity.Name},
                                          new Contracts.Common.PagedListRequestContract() {Take = 1});
            if (users != null)
            {
                model = users.Items.First();
            }
            return View(model);
        }

        [Authorize]
        public ActionResult BanUser(int userId)
        {
            var model =
                _service.GetUsers(new Contracts.User.UserFilterContract() {Id = userId}, null).Items.FirstOrDefault();
            return PartialView("_banUser", model);
        }

        [Authorize]
        public ActionResult UnBanUser(int userId)
        {
            var model =
                _service.GetUsers(new Contracts.User.UserFilterContract() {Id = userId}, null).Items.FirstOrDefault();
            return PartialView("_UnbanUser", model);
        }

        [Authorize]
        public ActionResult UnBan(int userId)
        {
            string message;
            string status;
            if (_service.UnBanUser(userId))
            {
                status = "OK";
                message = "Pomyślnie odbanowano użytkownika";
            }
            else
            {
                status = "ERROR";
                message = "Wystąpił błąd. Spróbuj później ;)";
            }
            return Json(new {status = status, message = message}, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult Ban(int userId, string banReason)
        {
            if (string.IsNullOrWhiteSpace(banReason))
            {
                return Json(new {status = "ERROR", message = "Musisz podać powód zbanowania."},
                            JsonRequestBehavior.AllowGet);
            }
            string message;

            string status;
            if (_service.BanUser(userId, banReason))
            {
                status = "OK";
                message = "Banowanie użytkownika zakończone sukcesem.";
            }
            else
            {
                status = "ERROR";
                message = "Banowanie użytkownika zakończone błędem. ";
            }
            return Json(new {status = status, message = message}, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public JsonResult Users(string term)
        {
            var userDict = _service.Users(term);
            var jsonList = new List<object> {};
            if (userDict.Count > 0)
            {
                foreach (var item in userDict)
                {
                    jsonList.Add(new
                        {
                            id = item.Key,
                            label = item.Value,
                            value = item.Value
                        });
                }
            }
            return Json(jsonList.ToArray(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult UserCard(int id)
        {
            UserContract model = default(UserContract);
            var users = _service.GetUsers(new Contracts.User.UserFilterContract() {Id = id},
                                          new Contracts.Common.PagedListRequestContract() {Take = 1});
            if (users != null)
            {
                model = users.Items.First();
            }
            return PartialView("_UserCard", model);
        }

        public ActionResult SetPermissions(int userId)
        {
            var model =
                _service.GetUsers(new Contracts.User.UserFilterContract() {Id = userId}, null).Items.FirstOrDefault();
            return PartialView("_setPermissions", model);
        }

        [HttpPost]
        public ActionResult SetPermissions(int userId, bool isMod, bool isAdmin)
        {
            string message = string.Empty;
            string status = string.Empty;
            if (_service.SetPermissions(userId, isMod, isAdmin))
            {
                status = "OK";
                message = "Nadawanie praw użytkownika zakończone sukcesem. ";
            }
            else
            {
                status = "ERROR";
                message = "Nadawanie praw użytkownika zakończone błędem. ";
            }
            return Json(new {message = message, status = status}, JsonRequestBehavior.AllowGet);
        }
    }
}

Isi2.Projekt/Isi2.Projekt.Web/Controllers/EntryController.cs
using Isi2.Projekt.Contracts;
using Isi2.Projekt.Web.Code;
using Isi2.Projekt.Contracts.User;
using Isi2.Projekt.Web.Helpers;
using Isi2.Projekt.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Isi2.Projekt.Contracts.Common;
using Castle.Windsor;
using System.IO;
using Isi2.Projekt.Contracts.Entry;
using Isi2.Projekt.Contracts.Comment;

namespace Isi2.Projekt.Web.Controllers
{
    public class EntryController : Controller
    {
        private readonly IService service = WindsorContainerAccess.GetContainer().Resolve<IService>();

        public ActionResult Index(int page = 1)
        {
            var result = service.GetEntries(
                new EntryFilterContract
                    {
                        Published = true,
						Username=User.Identity.Name,
                        Deleted = false
                    },
                new PagedListRequestContract {Page = page - 1, PageSize = 10, Take = 10});
            return View(result);
        }

        public ActionResult Others(int page = 1)
        {
            var result = service.GetEntries(
                new EntryFilterContract
                    {
                        Published = false,
						Username=User.Identity.Name,
                        Deleted = false
                    },
                new PagedListRequestContract {Page = page - 1, PageSize = 10, Take = 10});
            return View(result);
        }

        [Authorize]
        [AccessGroup]
        [HttpGet]
        public void HideImage(int imageId)
        {
            service.HideImage(imageId);
            //return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult AddToMain(int imageId)
        {
            service.AddToMain(imageId);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public ActionResult UploadImage()
        {
            return View();
        }

        [Authorize]
        public ActionResult GetFavouritesImagesForUser(int page = 1)
        {
            string userName = User.Identity.Name;
            int id = service.GetUsers(new UserFilterContract { Login = userName }, null).Items.First().Id;
            var result = service.GetFavouritesEntriesForUser(new EntryFilterContract { Id = id, Username = User.Identity.Name }, new PagedListRequestContract { Page = page - 1, PageSize = 10, Take = 10 });
            return View(result);
        }

        [Authorize]
        public ActionResult AddComment(int entryId, string text, int userId)
        {
            int idusera = service.GetUsers(new UserFilterContract { Id = userId }, null).Items.First().Id;
            var entry = service.GetEntries(new EntryFilterContract { Id = entryId }, null).Items.First().Id;
            var result = service.AddComment(new CommentContract()
            {
                EntryId = entry,
                UserId = idusera,
                Date = DateTime.Now,
                Text = text,
            });
            return View();
        }

        [HttpPost]
        public JsonResult Comments(int entryId)
        {
               var result = service.GetComments(
               new CommentFilterContract { EntryId = entryId },

               new PagedListRequestContract { Page = 0, PageSize = 10, Take = 10 });
                var jsonList = new List<object> { };
                if (result.Count > 0)
                {
                    result.Success = true;
                    foreach (var item in result.Items)
                     {
                        jsonList.Add(new
                        {
                        id = item.Id,
                        text = item.Text,
                        date = item.Date.ToShortDateString(),
                        user_name = item.UserName,
                        voted_for = service.CommentAlreadyVotedFor(service.GetUsers(new UserFilterContract { Login = item.UserName }, null).Items.First().Id,item.Id),
                        votes_number = service.CommentVotesNumber(service.GetUsers(new UserFilterContract { Login = item.UserName }, null).Items.First().Id,item.Id)  //user id service.GetUsers(new UserFilterContract { Login = userName }, null).Items.First().Id
                    });
                    }
                }
                //testowe wygenerowanie komentarzy //TODO: usunąć po testach
                //else 
                //{
                //    result.Success = true;
                //    for(int i=0;i<10;i++)
                //        jsonList.Add(new
                //        {
                //        id = 1,
                //        text = "testujeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br/><br/><br/><br/>Symulacja długich komentarzy.",
                //        date = DateTime.Now.ToShortDateString(),
                //        user_name = "testowo" });
                    
                //}
               
            return Json(jsonList.ToArray(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public ActionResult UploadImage(ImageUploadModel model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid && file != null)
            {
                try
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    //dodawanie obrazka
                    var result = service.AddEntry(new EntryContract()
                        {
                            Title = string.Empty,
                            AuthorId =
                                service.GetUsers(new Contracts.User.UserFilterContract {Login = model.AuthorId}, null).Items[0].Id,
                            Created = DateTime.Now,
                            Path = file.FileName
                        });
                    if (result.Success)
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Wystąpił błąd, spróbuj ponownie");
                }
            }
            return View();
        }

        [Authorize]
        public ActionResult AddImageToFavourite(int entryId,string userLogin)
        {
            if (service.ImageAlreadyInFavourites(entryId, userLogin)){
                return View();
            }
            int id = service.GetUsers(new UserFilterContract{Login = userLogin}, null).Items.First().Id;
            var entry = service.GetEntries(new EntryFilterContract { Id = entryId }, null).Items.First();
            service.AddImageToFavourites(entry, id);
            return View();          
        }

        [Authorize]
        public ActionResult VoteForEntry(int entryId, string userLogin)
        {         
            if (!service.EntryAlreadyVotedFor(entryId, userLogin)){
                return View();
            }
            int id = service.GetUsers(new UserFilterContract { Login = userLogin }, null).Items.First().Id;
            var entry = service.GetEntries(new EntryFilterContract { Id = entryId }, null).Items.First();
            service.VoteForEntry(entry, id);
            return View();
        }

        [Authorize]
        public ActionResult VoteForComment(string userName, int commentId)
        {
            int userId = service.GetUsers(new UserFilterContract { Login = userName }, null).Items.First().Id;
            //throw new DivideByZeroException();
            if (service.CommentAlreadyVotedFor(userId,commentId)){
                return View();
            }
            service.AddVoteForComment(userId, commentId);
            return View();
        }
    }
}

Isi2.Projekt/Isi2.Projekt.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Isi2.Projekt.Contracts;
using Isi2.Projekt.Contracts.Common;
using Isi2.Projekt.Contracts.Entry;
using Isi2.Projekt.Web.Helpers;
using Isi2.Projekt.Web.Models.ViewModels;

namespace Isi2.Projekt.Web.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /User/
        private IService _service = WindsorContainerAccess.GetContainer().Resolve<IService>();
        public ActionResult Index(string userName ="", int page = 1)
        {

            if (string.IsNullOrWhiteSpace(userName))
            {
                userName = User.Identity.Name;
            }
            UserViewModel model = new UserViewModel();
            UserContract user = default(UserContract);
            var users = _service.GetUsers(new Contracts.User.UserFilterContract() { Login = userName },
                                          new Contracts.Common.PagedListRequestContract() { Take = 1 });
            if (users != null)
            {
                user = users.Items.First();
                model.User = user;
            }
            else
            {
                return View("UserNotFound");
            }
            var userEntries = _service.GetEntries(new EntryFilterContract() {UserId = model.User.Id},
                                                 new PagedListRequestContract {Page = page - 1, PageSize = 5, Take = 5});
            
            model.Entries = userEntries;
            return View("Profile", model);
        }

    }
}

Isi2.Projekt/Isi2.Projekt.Web/Views/Shared/_Entry.cshtml
@using Isi2.Projekt.Contracts
@model Isi2.Projekt.Contracts.EntryContract
@{      
    Func<bool> IsMod = () =>
      {
          bool result = false;
          if (!User.Identity.IsAuthenticated)
              return false;
          result = (Session["isMod"] as bool?) == true
          || (Session["isAdmin"] as bool?) == true;
          return result;
      };

    Func<string> GenerateHash = () => Isi2.Projekt.Web.Helpers.AccessGroupSecurityProvider
      .Instance.GenerateHash(((UserContract)Session["currentUser"]).Id);
}
<div class="entry">
    <hr />
    <div style="text-align: center;">
        <a href="#">
            <img src="@Url.Content("~/Content/images/" + @Model.File)" class="img-polaroid" style="max-width: 100%;">
        </a>
    </div>

    <div style="height: 40px; margin-top: 20px;">
        <h6 style="float: left;">dodano: @Model.Created.ToShortDateString() przez <strong>@Html.ActionLink(Model.Username, "Index", "User", new { userName = Model.Username }, null)</strong></h6>

        <input type="hidden" value="@Model.Id" />
        <input type="button" style="float: right;" class="btn btn-inverse" id="@(Model.Id + "koment")" value="Komentarze &raquo;" />
        <h6 style="float: left;">
            <div class="Komentarze" id="comt"></div>
        </h6>
        <span style="float: right;">
            @if (User.Identity.IsAuthenticated)
            {

                if (Model.EntryAlreadyVotedFor)
                {
                <img src="../../Content/img/plus01.jpg" onmouseover="this.src='../../Content/img/plus02.jpg'" onmouseout="this.src='../../Content/img/plus01.jpg'" id="@(Model.Id + "plus")" style="margin-right:5px; " onclick="this.onmouseout=''; this.disabled=true; document.getElementById('@(Model.Id + "plusNum")').innerHTML=parseInt(document.getElementById('@(Model.Id + "plusNum")').innerHTML)+1; this.onclick='' " ></img>
                }
                else
                {
                <img src="../../Content/img/plus02.jpg" style="margin-right: 5px;"></img>
                }
                <span id="@(Model.Id + "plusNum")" style="color:Green; font-size:1.4em; font-style: oblique; margin-right:15px;" >
                    @Model.VotesNumber
                </span>                
                if (!Model.ImageAlreadyInFavourites)
                {
                <button class="btn btn-inverse2" id="@(Model.Id + "btn")" style="margin-right:10px;" onclick="this.disabled=true" >Lubie </button>
                }
                else
                {
                <button class="btn btn-inverse2" disabled="disabled" style="margin-right: 5px">Lubie </button>
                }
            }
            @if (IsMod())
            {
                <input type="button" value="Ukryj" class="btn btn-danger" id="@Model.Id" title="Ukryj" />
                //<a href ="#" class="btn btn-danger" id="@Model.Id"></a>
                //@Html.ActionLink("Ukryj", "HideImage", new { imageId = Model.Id, h = GenerateHash() }, new { @class = "btn btn-danger" });
            
                if (Model.Published == false)
                {
                    @Html.ActionLink("Główna!", "AddToMain", new { imageId = Model.Id }, new { @class = "btn btn-danger" });
                }
            }
        </span>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function () {
        $('#@(Model.Id + "btn")').bind('click', function () {
            $.ajax({
                url: '@Url.Action("AddImageToFavourite", "Entry")',
                  data: { entryId: '@Model.Id', userLogin: '@User.Identity.Name' },
                  dataType: 'json',
                  success: function (result) {
                  },
              })
        })
    });

    $(document).ready(function () {
      $('#@(Model.Id + "plus")').bind('click', function () {
        $.ajax({
            url: '@Url.Action("VoteForEntry", "Entry")',
                  data: { entryId: '@Model.Id', userLogin: '@User.Identity.Name' },
                  dataType: 'json',
                  success: function (result) {
                  },
              })
           })
      });

        $('#@(Model.Id + "koment")').click(function () {
            var dd = $(this).next();
            var ido = $(this).prev().val();
            var text = "";
            $(dd).slideToggle("slow");
            $.ajax({
                type: 'post',
                url: '@Url.Action("Comments", "Entry")',
                            data: { entryId: ido },
                            dataType: 'json',
                            success: function (result) {
                                dd.html(text);                          
                                for (var i = 0; i < result.length; i++) {
                                    $(dd).append("<div style=\"margin-bottom:8px; background-color:#D8F6CE; border-radius: 8px; padding:3px 10px 3px 10px;\"><p>dodano: " + result[i].date + " przez <a href=\"/User?userName=" + result[i].user_name + "\">" + result[i].user_name + "</a></p><p>" + result[i].text + "</p></div>");
                                    if(!result[i].voted_for){
                                    var entryId = result[i].id;
                                        $(dd).append('<img src="../../Content/img/plus01.jpg" onmouseover="this.src=\'../../Content/img/plus02.jpg\'" onmouseout="this.src=\'../../Content/img/plus01.jpg\'" id="@(Model.Id + "plusCom")'+i+'" style="margin-right:5px; " onclick="this.onmouseout=\'\'; this.disabled=true; document.getElementById(\'@(Model.Id + "plusComNum")'+i+'\').innerHTML=parseInt(document.getElementById(\'@(Model.Id + "plusComNum")'+i+'\').innerHTML)+1; this.onclick=\'\' "/>').click(function () {
                                            $.ajax({
                                                type: 'post',
                                                url: '@Url.Action("VoteForComment", "Entry")',
                                                data: { userName: "@User.Identity.Name", commentId: entryId },
                                                dataType: 'json',
                                                success: function (result) {
                                                    alert("test");
                                                }
                                            });
                                        });
                                    }
                                    else{
                                        $(dd).append('<img src="../../Content/img/plus02.jpg" style="margin-right: 5px;"/>');
                                    }
                                    $(dd).append('<span id="@(Model.Id + "plusComNum")'+i+'" style="color:Green; font-size:1.4em; font-style: oblique; margin-right:15px;" >' + result[i].votes_number + '</span><br/>');
                                }                                
                                
                                $(dd).append('<textarea cols="20" id="@(Model.Id + "addkomTxt")" name="DodKomentTxt" placeholder="Treść komentarza..." rows="2"></textarea>')
                                $(dd).append('<input type="button" class="btn btn-inverse" id="@(Model.Id + "addkom")" value="Dodaj nowy komentarz">').click(function () {
                                    $.ajax({
                                        type: 'post',
                                        url: '@Url.Action("AddComment", "Entry")',
                                        data: { entryId: ido, text: $('#@(Model.Id + "addkomTxt")').val(), userId: '@Model.AuthorId' },
                                        dataType: 'json',
                                        success: function (result) {
                                            alert("test");
                                        }
                                    });
                                });
                                
                            },
                            error: function () {
                                alert("Błąd pobierania komentarzy");
                            }
                    });
        });



</script>

Isi2.Projekt/Isi2.Projekt.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="utf-8" />
    <title>Projekt</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />
     <link href="@Url.Content("~/Content/jquery.fancybox.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.fancybox.js")" type="text/javascript"></script>
    <style type="text/css">
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div id="content">
        <section class="navbar navbar-inverse navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              @Html.Partial("_Menu")
            </div>
          </div>
        </section>

        <section class="container">
            <div class="row">
              <div id="inner">
                
                @RenderBody()
                  </div>
            </div>
        </section>
    </div>
    
</body>
</html>

Isi2.Projekt/Isi2.Projekt.Web/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated)
{
    <form class="navbar-form pull-right form-inline" action="@Url.Action("LogOff", "Account")" method="post">
        <label class="checkbox">
            zalogowano jako: <strong>@Html.ActionLink(User.Identity.Name,"Index","User")</strong>
        </label>
        <button type="submit" class="btn btn-danger">Wyloguj</button>
    </form>
    
}
else
{
    <form class="navbar-form pull-right" style="margin-left: 10px;" action="@Url.Action("Register", "Account")" method="get">
        <button type="submit" class="btn btn-info">Zarejestruj</button>
    </form>
    <form class="navbar-form pull-right" action="@Url.Action("LogOn", "Account")" method="post">
        <input class="span2" type="text" placeholder="Login" name="UserName" />
        <input class="span2" type="password" placeholder="Hasło" name="Password" />
        <button type="submit" class="btn btn-success">Zaloguj</button>
    </form>
}

Isi2.Projekt/Isi2.Projekt.Web/Views/Shared/_Menu.cshtml
@using Isi2.Projekt.Contracts
@Html.ActionLink("Projekt", "Index", "Entry", null, new { @class = "brand" })

@{
    Func<string, string> IsActive = (link) =>
    {
        if (Request.RawUrl == link)
            return "active";
        return string.Empty;
        
    };

    Func<bool> IsAdmin = () =>
    {
        bool result = false; 
        result = (Session["isAdmin"] as bool?) == true;
        return result;
    };

    Func<string> GenerateHash = () => Isi2.Projekt.Web.Helpers.AccessGroupSecurityProvider
        .Instance.GenerateHash(((UserContract)Session["currentUser"]).Id);
}

<nav class="nav-collapse collapse">
    <ul class="nav">
        <li class="@IsActive(@Url.Action("Index", "Entry"))"><a href="@Url.Action("Index", "Entry")"><i class="icon-home icon-white"></i>&nbsp;Najlepsze</a></li>
        <li class="@IsActive(@Url.Action("Others", "Entry"))"><a href="@Url.Action("Others", "Entry")"><i class="icon-th-large icon-white"></i>&nbsp;Poczekalnia</a></li>
        @if (Request.IsAuthenticated)
        {
            if (IsAdmin()) { <li><a href="@Url.Action("Index", "Administrator", new { h=GenerateHash() })"><i class="icon-th-large icon-white"></i>&nbsp;Panel administratora</a></li> }
            <li class="@IsActive(@Url.Action("UploadImage", "Entry"))"><a href="@Url.Action("UploadImage", "Entry")"><i class="icon-plus icon-white"></i>&nbsp;Dodaj</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i>Panel użytkownika <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="@Url.Action("GetFavouritesImagesForUser", "Entry")"><i class="icon-star icon-white"></i>&nbsp;Ulubione</a></li>
                    <li><a href="@Url.Action("ChangePassword", "Account")">Zmiana hasła</a></li>
                    <li><a href="@Url.Action("Index", "User")"><i class="icon-user"></i>&nbsp;Mój Profil</a></li>
                </ul>
            </li>
        }
    </ul>
    @Html.Partial("_LogOnPartial")
</nav>